name: scratchpad-rag-cuda10
channels:
  - conda-forge
  - pytorch
  - huggingface
dependencies:
  # - python>=3.10
  # - pip
  # - pytorch
  - python>=3.8  # Ensure Python version is compatible with specified PyTorch and torchvision versions
  # - pip
  - pytorch==1.10.1
  # - torchvision==0.11.2
  # - torchaudio==0.10.1
  - cudatoolkit=10.2  # Specify the CUDA toolkit version
  # - transformers=4.36.2
  # - datasets=2.11.0
  # - xopen
  # - timm=0.4.12
  # - numpy
  # - pandas
  # - einops
  # - opt_einsum
  # - jupyter
  # - jupyterlab
  # - matplotlib
  # - omegaconf
  # - tqdm
  # - rich
  # - wandb
  # - pip:
  #   - bitsandbytes>=0.39.0
  #   - peft
   # - flash-attn  # --no-build-isolation
