pretrained_config:
  pretrained_model_name_or_path: 'gpt2'
  cache_dir: '/dfs/scratch1/common/pretrained_models' #'/juice/scr/scr110/scr/nlp/data/neo/hub/'
  return_dict: true
  quantization: false
  device_map: auto
  low_cpu_mem_usage: true
  torch_dtype: float16
  rope_theta: 10000.0